name: Appium Test with APK
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: appium/appium

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Start Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64

      - name: Install APK
        run: |
          adb wait-for-device
          adb install ./app/googleCalculator.apk  # APK precisa estar no repositório

      - name: Run Tests
        run: mvn test -DdeviceName=emulator-5554
