name: Appium Test with APK
on: [push]

permissions:
  contents: read
  actions: write

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: appium/appium:latest
      options: --user root -v /dev/kvm:/dev/kvm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Start Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 26
          arch: x86_64
          target: default
          profile: Nexus 4
          disable-animations: true
          emulator-options: 
            -no-snapshot 
            -no-window 
            -gpu swiftshader_indirect 
            -noaudio 
            -no-boot-anim 
            -camera-back none 
            -qemu 
            -enable-kvm 
            -metrics-collection 
            -no-metrics
          script: |
            # Wait for emulator to start
            echo "Waiting for emulator to boot..."
            adb wait-for-device
            echo "Device found, waiting for boot completion..."
            while [ "$(adb shell getprop sys.boot_completed | tr -d '\r')" != "1" ]; do
              sleep 5
              echo "Still waiting for boot..."
            done
            echo "Emulator fully booted!"

      - name: Verify Emulator
        run: |
          adb devices
          adb shell getprop ro.build.version.release

      - name: Install APK
        run: |
          adb install -t -g ./app/googleCalculator.apk
          adb shell pm list packages | grep calculator

      - name: Run Tests
        run: mvn test -DdeviceName=emulator-5554
