name: Appium Test with APK
on: [push]

permissions:
  contents: read
  actions: write

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: appium/appium:latest
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Start Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          profile: Nexus 6
          disable-animations: true
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: adb devices

      - name: Install APK
        run: |
          adb wait-for-device
          adb install ./app/googleCalculator.apk  # APK precisa estar no repositório
          adb shell pm list packages | grep calculator

      - name: Run Tests
        run: mvn test -DdeviceName=emulator-5554
