name: Appium CICD Test
on: [push, pull_request]

jobs:
  run-android-tests-remote:
    env:
      ANDROID_PROFILE: Nexus 6
      ANDROID_TARGET: google_apis
      ANDROID_API_LEVEL: 28
      ANDROID_ARCH: x86_64
      
    runs-on: ubuntu-latest
    outputs:
      maven_tests: ${{ steps.maven_tests.outcome }}
      
    steps:
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: pull the project in to the runner
        uses: actions/checkout@v4
          
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: mvn install -DskipTests

      - name: Setup and Run Appium Server (run in background)
        run: |
          chmod +x ./scripts/prepareAppiumServer.sh
          ./scripts/prepareAppiumServer.sh

      - name: Start android emulator and run tests
        id: maven_tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.ANDROID_API_LEVEL }}
          target: ${{ env.ANDROID_TARGET }}
          arch: ${{ env.ANDROID_ARCH }}
          profile: ${{ env.ANDROID_PROFILE }}
          script: | 
            # Faz o script falhar ao primeiro erro
            set -e

            # Define ação ao detectar erro em qualquer linha
            trap 'echo "🛑 Houve um erro. Encerrando emulator-5556..."; /usr/local/lib/android/sdk/platform-tools/adb -s emulator-5556 emu kill >/dev/null 2>&1 || true' ERR

            chmod +x ./scripts/start_emulator_2.sh
            ./scripts/start_emulator_2.sh

            chmod +x ./scripts/uploadAPK.sh
            ./scripts/uploadAPK.sh

            mvn test -Dsurefire.suiteXmlFiles=src/test/resources/testng-local.xml

            # Se chegou até aqui, mata o emulador secundário também
            echo " Finalizando emulator-5556"
            /usr/local/lib/android/sdk/platform-tools/adb -s emulator-5556 emu kill || true
          
      - name: Upload results as artifacts
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: allure-results-android-remote
          path: ./target/allure-results

  run-android-tests-saucelabs:
    runs-on: ubuntu-latest
    needs: run-android-tests-remote
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Run Tests on Sauce Labs
        run: mvn test -Dsurefire.suiteXmlFiles=src/test/resources/testng-cloud.xml
      
      - name: Upload results as artifacts
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: allure-results-android-cloud
          path: ./target/allure-results
        
  deploy-report:
      if: always()
      name: Generate and deploy Allure Report
      needs: [run-android-tests-remote, run-android-tests-saucelabs]
      runs-on: ubuntu-latest
      env:
        GH_PAGES_URL: https://clark-ewerton.github.io/mobile-test-automation-lab
      
      steps:
      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Download Android remote results artifacts
        if: always()
        uses: actions/download-artifact@master
        with:
          name: allure-results-android-remote
          path: target/allure-results

      - name: Download Android cloud results artifacts
        if: always()
        uses: actions/download-artifact@master
        with:
          name: allure-results-android-cloud
          path: target/allure-results

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

      - name: Post the link to the report
        if: always()
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Test report'
          state: ${{ needs.run-android-tests-remote.outputs.maven_tests == 'success' && needs.run-android-tests-saucelabs.outputs.maven_tests == 'success' && 'success' || 'failure' }}
          sha: ${{github.event.pull_request.head.sha || github.sha}}
          target_url: ${{ env.GH_PAGES_URL }}/${{github.run_number}}/
