name: Appium Test with APK
on: [push]

permissions:
  contents: read
  actions: write

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: appium/appium:latest
      options: --user root -v /dev/kvm:/dev/kvm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Start Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          profile: Nexus 6
          disable-animations: true
          emulator-options: 
            -no-snapshot 
            -no-window 
            -gpu swiftshader_indirect 
            -noaudio 
            -no-boot-anim 
            -camera-back none 
            -qemu 
            -enable-kvm 
            -metrics-collection 
            -no-metrics
          script: 
            adb wait-for-device
            while ! adb shell getprop sys.boot_completed | grep -q 1; do sleep 1; done

      - name: Verify Emulator
        run: |
          adb devices
          adb shell getprop ro.build.version.release

      - name: Install APK
        run: |
          adb install -t -g ./app/googleCalculator.apk
          adb shell pm list packages | grep calculator

      - name: Run Tests
        run: mvn test -DdeviceName=emulator-5554
