name: Appium Android Test
on: [push, pull_request]

jobs:
  run-mobile-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          
      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: pull the project in to the runner
        uses: actions/checkout@v4

      - name: Setup Appium (run in background)
        run: |
          npm install -g appium
          appium -v
          appium driver list --installed
          appium driver install uiautomator2
          nohup appium --log-level warn --log-timestamp --local-timezone > appium.log 2>&1 &
          sleep 10
          curl http://127.0.0.1:4723/wd/hub/sessions || echo "Appium check failed"

      - name: start android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 25
          target: google_apis
          arch: x86_64
          script: |
            adb wait-for-device
            adb shell input keyevent 82
            adb devices
            adb install -t -g ./app/googleCalculator.apk  # APK precisa estar no repositório
            adb shell pm list packages | grep calculator
                  # Roda testes (gera /target/allure-results)
            mvn test -Dsurefire.suiteXmlFiles=src/test/resources/testng-local.xml

            # Gera relatório Allure (em /target/site/allure-maven-plugin)
            mvn allure:report

            # Copia relatório para fora do runner (se necessário)
            mkdir -p /tmp/allure-report
            cp -R ./target/site/allure-maven-plugin/* /tmp/allure-report/
            ls -R /tmp/allure-report/  # Debug (opcional)
    
          post-checkout: |
            # Executado APÓS o script principal, mas ANTES do emulador ser desligado
            mkdir -p ./artifacts/allure-report
            cp -R /tmp/allure-report/* ./artifacts/allure-report/
            ls -R ./artifacts/  # Verifica se os arquivos foram copiados

      - name: Upload Allure report artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: ./artifacts/allure-report/

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./artifacts/allure-report/
