name: Appium CICD Test
on: [push, pull_request]

jobs:
  run-android-tests-remote:
    env:
      ANDROID_PROFILE: Nexus 6
      ANDROID_TARGET: google_apis
      ANDROID_API_LEVEL: 28
      ANDROID_ARCH: x86_64
      
    runs-on: ubuntu-latest
    outputs:
      maven_tests: ${{ steps.maven_tests.outcome }}
      
    steps:
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: pull the project in to the runner
        uses: actions/checkout@v4
          
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: mvn install -DskipTests

      - name: Setup and Run Appium Server (run in background)
        run: |
          chmod +x ./scripts/prepareAppiumServer.sh
          ./scripts/prepareAppiumServer.sh

      - name: Start android emulator and run tests
        id: maven_tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.ANDROID_API_LEVEL }}
          target: ${{ env.ANDROID_TARGET }}
          arch: ${{ env.ANDROID_ARCH }}
          profile: ${{ env.ANDROID_PROFILE }}
          script: | 
            chmod +x ./scripts/uploadAPK.sh
            ./scripts/uploadAPK.sh
            mvn test -Dsurefire.suiteXmlFiles=src/test/resources/testng-local.xml

      - name: Prepare Allure Results (Remote)
        run: |
          mkdir -p allure-results/remote  # Cria a estrutura
          cp -r target/allure-results/* allure-results/remote  # Copia os resultados
      
      - name: Upload Allure Results (Remote)
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: allure-results-remote
          path: allure-results/remote

  run-android-tests-saucelabs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Run Tests on Sauce Labs
        run: mvn test -Dsurefire.suiteXmlFiles=src/test/resources/testng-cloud.xml

      - name: Prepare Allure Results (Remote)
        run: |
          mkdir -p allure-results/cloud  # Cria a estrutura
          cp -r target/allure-results/* allure-results/cloud  # Copia os resultados
      
      - name: Upload Allure Results (Sauce Labs)
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: allure-results-saucelabs
          path: allure-results/cloud
        
  deploy-report:
      if: always()
      name: Generate and deploy Allure Report
      needs: [run-android-tests-remote, run-android-tests-saucelabs]
      runs-on: ubuntu-latest
      env:
        GH_PAGES_URL: https://clark-ewerton.github.io/mobile-test-automation-lab
      
      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Allure Results
        uses: actions/download-artifact@master
        with:
          path: allure-results

      - name: Merge Allure Results
        run: |
          mkdir -p merged-results
          cp -r allure-results/remote/* merged-results/ || true
          cp -r allure-results/cloud/* merged-results/ || true

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: merged-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

      - name: Post the link to the report
        if: always()
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Test report'
          state: ${{ needs.run-android-tests-remote.outputs.maven_tests == 'success' && needs.run-android-tests-saucelabs.outputs.maven_tests == 'success' && 'success' || 'failure' }}
          sha: ${{github.event.pull_request.head.sha || github.sha}}
          target_url: ${{ env.GH_PAGES_URL }}/${{github.run_number}}/
