name: Appium Android Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    container:
      image: appium/appium:latest
      options: --user root -v /dev/kvm:/dev/kvm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Initialize ADB
        run: |
          adb kill-server
          adb start-server
          echo "ADB Version:"
          adb version

      - name: Start Emulator with Retry
        id: emulator
        uses: reactivecircus/android-emulator-runner@v2
        continue-on-error: true
        with:
          api-level: 31
          arch: x86_64
          profile: Nexus 6
          disable-animations: true
          emulator-options: >-
            -no-snapshot
            -no-window
            -gpu swiftshader_indirect
            -no-audio
            -no-boot-anim
            -camera-back none
            -no-metrics
          script: |
            echo "=== EMULATOR STARTUP SEQUENCE ==="
            echo "Initializing ADB connection..."
            adb reconnect offline
            adb wait-for-device
            echo "Waiting for full boot..."
            for i in {1..30}; do
              if adb shell getprop sys.boot_completed | grep -q "1"; then
                echo "Emulator fully booted!"
                exit 0
              fi
              sleep 5
              echo "Boot in progress... Attempt $i/30"
              adb reconnect device 2>/dev/null
            done
            echo "Error: Emulator failed to boot within timeout"
            exit 1

      - name: Verify Emulator Connection
        if: steps.emulator.outcome == 'success'
        run: |
          echo "Listando dispositivos conectados:"
          adb devices -l
          echo "Dispositivo padrão:"
          adb get-serialno
          echo "Propriedades do dispositivo:"
          adb shell getprop

      - name: Install APK
        if: steps.emulator.outcome == 'success'
        run: |
          adb install -t -g ./app/googleCalculator.apk
          echo "APKs instalados:"
          adb shell pm list packages

      - name: Run Tests
        if: steps.emulator.outcome == 'success'
        run: |
          DEVICE=$(adb devices | grep emulator | awk '{print $1}')
          echo "Executando testes no dispositivo: $DEVICE"
          mvn test -DdeviceName=$DEVICE

      - name: Emulator Troubleshooting
        if: steps.emulator.outcome != 'success'
        run: |
          echo "=== TROUBLESHOOTING ==="
          echo "Processos emulador:"
          ps aux | grep emulator
          echo "Dispositivos ADB:"
          adb devices -l
          echo "Logs do emulador:"
          adb logcat -d | tail -50
          echo "Verificando KVM:"
          grep -c -w "vmx\|svm" /proc/cpuinfo
          echo "Arquivos do emulador:"
          ls -la $ANDROID_HOME/emulator
          false # Force step failure
