name: Android Emulator Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: appium/appium:latest
      options: --user root -v /dev/kvm:/dev/kvm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Initialize ADB
        run: |
          adb kill-server
          adb start-server
          adb devices

      - name: Start Emulator (API 29)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29  # API mais estável
          arch: x86_64
          profile: Nexus 5
          disable-animations: true
          emulator-options: >-
            -no-snapshot
            -no-window
            -gpu swiftshader_indirect
            -no-audio
            -no-boot-anim
            -camera-back none
            -no-metrics
            -accel on
            -memory 2048
            -partition-size 1024
          script: |
            echo "Waiting for device..."
            adb wait-for-device
            echo "Waiting for boot completion..."
            for i in {1..60}; do
              if adb shell getprop sys.boot_completed | grep -q "1"; then
                echo "Emulator ready!"
                exit 0
              fi
              sleep 5
              echo "Attempt $i/60 - Boot in progress..."
              adb reconnect
            done
            echo "Error: Emulator failed to boot"
            exit 1

      - name: Verify connection
        run: |
          adb devices
          adb shell getprop ro.build.version.release

      - name: Install APK
        run: |
          adb install -r -t -g ./app/googleCalculator.apk
          adb shell pm list packages | grep calculator

      - name: Run tests
        run: |
          mvn test -DdeviceName=$(adb devices | grep emulator | awk '{print $1}')

      - name: Collect logs on failure
        if: failure()
        run: |
          echo "=== DEBUG INFO ==="
          adb logcat -d > emulator.log
          cat emulator.log
          ps aux | grep -i emulator
          ls -la $ANDROID_HOME/emulator
